[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sws_api_wrapper"
version = "0.1.4"
license = {file = "LICENSE.txt"}
keywords = ["sws", "sowesign", "so we sign"]
dependencies = [
  "user_agent"
]
description = "An API wrapper for So We Sign"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/avivi55/SWS"
Issues = "https://github.com/avivi55/SWS/issues"