[build-system]
requires = ['setuptools>=68.2']
build-backend = 'setuptools.build_meta'


[project]
name = "ezdata"
version = "0.0.8"
authors = [
  { name = "Asger Jon Vistisen", email = "asgerjon2@gmail.com" },
]
description = "A simple base class for dataclasses"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/AsgerJon/ezdata"
"Bug Tracker" = "https://github.com/AsgerJon/ezdata"
