[project]
name = "py_utils_khabibullin.m.m"
version = "0.0.4"
authors = [
  { name="Example Author", email="khabibullin.m.m@gmail.com.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE.txt"}

[project.urls]
Homepage = "https://github.com/"
Issues = "https://github.com/"

[project.scripts]  # Optional
sample = "app:main"

# This is configuration specific to the `setuptools` build backend.
# If you are using a different build backend, you will need to change this.
[tool.setuptools]
# If there are data files included in your packages that need to be
# installed, specify them here.
package-data = {"sample" = ["*.dat"]}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"