[project]
name = "dinky-calendar"
version = "0.1.1"
description = "Calendar widget for the dinky dashboard"
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "Julian Prester"}]
license = {text = "MIT"}
dependencies = [
    "dinky",
    "pluggy",
    "Pillow",
    "caldav",
    "setuptools"
]

[project.optional-dependencies]
test = ["pytest"]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
