[tool.poetry]
name = "shopping-cart-387dd67aa803"
version = "0.1.0"
description = "Simple shopping cart that lets you add items and display the state of the cart"
authors = ["None"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
requests-mock = "^1.11.0"
flake8 = "^7.0.0"
black = "^23.12.1"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
