[build-system]
requires = [
    "pdm-backend",
    "regex",
    "urlpath",
    "packaging",
]
build-backend = "pdm.backend"

[project]
name = "py_git_auto_version"
dynamic = []
description = "A project built with PDM-Backend"
authors = [
    { name = "Michael Gooch", email = "goochmi@gmail.com" },
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "networkx>=3.2.1",
    "regex>=2023.12.25",
    "typing-extensions>=4.9.0",
    "urlpath>=1.2.0",
]
version = "1.0.0"

[project.license]
text = "The Unlicense"

[project.optional-dependencies]
extras = [
    "rich>=13.7.0",
]
validation = [
    "pydantic<1.11,>1.10",
    "packaging>=23.2",
]
docs = [
    "sphinx>=7.2.6",
]
dev = [
    "pdm>=2.12.1",
    "nox>=2023.4.22",
    "packaging>=23.2",
    "rich>=13.7.0",
]
lint = [
    "pylint>=3.0.3",
    "flake8>=7.0.0",
    "flake8-import-order>=0.18.2",
]
test = [
    "pytest>=7.4.4",
    "click>=8.1.7",
]

[project.scripts]
find-import-cycles = "pyimportcyclefinder.cli:main"

[project.urls]
Repository = "https://github.com/kotoroshinoto/PyImportCycleFinder"

[tool.pdm.version]
source = "call"
getter = "py_git_auto_version.version_generators:generate_version_string_for_scenario"
write_to = "py_git_auto_version/_version.py"
write_template = "__version__ = '{}'\n"
