[build-system]
requires = ["setuptools @ git+https://github.com/pypa/setuptools.git@main"]
build-backend = "setuptools.build_meta"

[project]
name = "lambchop"
description = "My package description"
version = "0.0.4"
authors = [{name = "bohemdev"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
    "anyio",
    "dill",
    "typer[all]"
]

[project.optional-dependencies]
"cli" = ["typer[all]"]

[project.scripts]
lambchop = "lambchop.cli:app"