[tool.poetry]
name = "detadoc"
version = "0.1.6"
description = ""
authors = ["Daniel Arantes <arantesdv@me.com>"]
exclude = ['src', '.space', 'Spacefile', '.env', 'dev.py']

[tool.poetry.dependencies]
python = "^3.9"
spacestar = "^0.2.1"
bcrypt = "^4.1.1"
email-validator = "^2.1.0"
ormspace = "^0.2.3"
hx-markup = "^0.2.2"
httpx = {extras = ["http2"], version = "^0.26.0"}
requests = "^2.31.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
