[tool.poetry]
name = "inoopa_utils"
description = "Collection of utils used at Inoopa."
version = "1.13.2"
authors = ["Dev Inoopa <dev@inoopa.com>"]
packages = [{ include = "inoopa_utils" }]
repository = "https://bitbucket.org/inoopa/inoopa_utils/"
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"
iniconfig = "^2.0.0"
# TODO: Won't work for now, to fix!
# torch = [
#     { version = "^2", source = "pytorch", markers = "sys_platform == 'linux'" },
#     { version = "^2", source = "PyPI", markers = "sys_platform == 'darwin'" },
# ]
deepparse = "0.9.9"
pandas = "^2.0.3"
pendulum = "^2.1.2"
PyMySQL = "^1.0.0"
python-dotenv = "1.0.0"
rabbitpy = "^2.0.1"
SQLAlchemy = "^2.0.0"
typesense = "^0.18.0"
pymongo = "^4.6.1"
boto3 = "^1.34.18"

# [[tool.poetry.source]]
# name = "pytorch"
# url = "https://download.pytorch.org/whl/cpu/"
# priority = "explicit"
