[project]
name = "dinky"
version = "0.1"
description = "Home dashboard for the Inkyframe"
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "Julian Prester"}]
license = {text = "MIT"}
dependencies = [
    "pydantic",
    "pluggy",
    "Pillow"
]

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools]
packages = ["dinky"]