image: python:3.10

cache:
  paths:
    - .cache
    - .venv

before_script:
  - pip install pipenv
  - pipenv install --deploy --dev

stages:
  - lint
  - test
  - build
  - release
  - publish
  - containerize

lint:
  stage: lint
  script:
    - pipenv run flake8 src tests

test:
  stage: test
  script:
    - pipenv run pytest

build:
  stage: build
  script:
    - pipenv run hatch build
  artifacts:
    paths:
      - dist/

release:
  stage: release
  only:
    - main
  script:
    - git checkout main
    - git reset --hard $CI_COMMIT_SHA
    - pipenv run semantic-release version


publish:
  stage: publish
  only:
    - tags
  script:
    - pipenv run twine upload dist/*

containerize:
  stage: containerize
  image: docker:25.0.0
  services:
    - docker:25.0.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  only:
    - main
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx inspect --bootstrap
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG . --push
