[tool.poetry]
name = "internal"
version = "0.1.0"
description = ""
authors = ["Ray <ray@RayMBP16>"]
readme = "README.md"
packages = [{include = "internal", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.109.0"
arrow = "^1.3.0"
pydantic-settings = "^2.1.0"
watchtower = "^3.0.1"
motor = "^3.3.2"
httpx = "^0.26.0"
beanie = "^1.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
