[project]
name = "coating"
version = "0.0.2"
authors = [
  { name="Pieli", email="pieli.dev@gmail.com" },
]
description = "A filter with an pointer interface ðŸ¦"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Environment :: Console",

    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: System Administrators",

    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries",
    "Topic :: Scientific/Engineering :: Visualization",
]

dependencies = [
  "beautifulsoup4==4.12.2",
  "bs4==0.0.1",
  "lxml==4.9.3",
  "soupsieve==2.5",
]

keywords = ["vim", "bash", "cli", "unix", "rice", "tui", "hci", "interaction", "unix-philosophy"]

[project.scripts]
coating = "coating.view:main"


[project.urls]
"Homepage" = "https://github.com/Pieli/coating"
"Bug Tracker" = "https://github.com/Pieli/coating/issues"



