[project]
name = "novelai_gen"
version = "0.1.0"
description = "Gen Image From Novelai"
authors = [
    { name = "sudoskys", email = "coldlando@hotmail.com" },
]
dependencies = [
    "elara>=0.5.5",
    "redis>=5.0.1",
    "loguru>=0.7.2",
    "pydantic-settings>=2.1.0",
    "pydantic>=2.5.3",
    "sentry-sdk>=1.39.2",
    "httpx>=0.26.0",
    "shortuuid>=1.0.11",
    "Pillow>=10.2.0",
    "curl-cffi>=0.5.10",
    "dynaconf>=3.2.4",
    "fastapi>=0.109.0",
    "uvicorn[standard]>=0.26.0",
]
requires-python = ">=3.8"
readme = "README.md"

[project.license]
text = "MIT"

[project.optional-dependencies]
testing = [
    "pytest>=7.4.4",
]

[tool.pdm]
distribution = true

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
