[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "magcopy"
dynamic = ["version"]
requires-python = ">= 3.6"
authors = [
  {name = "Ada√≠as Magdiel", email = "eu@adaiasmagdiel.com"},
]
description = "magcopy is a command-line utility that simplifies the copy and move operations of files and directories between terminal windows."
readme = "README.md"
keywords = ["file management", "command-line utility", "clipboard", "copy and move", "terminal interaction"]
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Console",
	"Intended Audience :: Developers",
	"Intended Audience :: End Users/Desktop",
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.6",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"Topic :: Software Development :: Build Tools",
]

[project.urls]
Homepage = "https://github.com/AdaiasMagdiel/magcopy"
Documentation = "https://github.com/AdaiasMagdiel/magcopy/blob/main/README.md"
Repository = "https://github.com/AdaiasMagdiel/magcopy"
Issues = "https://github.com/AdaiasMagdiel/magcopy/issues"

[project.scripts]
magcopy = "magcopy.main:main"

[tool.setuptools.dynamic]
version = {attr = "magcopy.__version__"}
