# ðŸš€ Gradio YOLOv8 Det, GPL-3.0 license
# åŸºäºŽ Gradio çš„ YOLOv8 é€šç”¨è®¡ç®—æœºè§†è§‰æ¼”ç¤ºç³»ç»Ÿ
# é›†æˆç›®æ ‡æ£€æµ‹ã€å›¾åƒåˆ†å‰²å’Œå›¾åƒåˆ†ç±»äºŽä¸€ä½“ï¼Œå¯è‡ªå®šä¹‰æ£€æµ‹æ¨¡åž‹


[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "gradio-yolov8-det"
version = "v2.2.0-alpha01"
requires-python = ">=3.8"
description = "åŸºäºŽ Gradio çš„ YOLOv8 é€šç”¨è®¡ç®—æœºè§†è§‰æ¼”ç¤ºç³»ç»Ÿ"
readme = "README.md"
license = { "text" = "GPL-3.0" }
keywords = ["YOLOv8", "Gradio", "ç›®æ ‡æ£€æµ‹", "å›¾åƒåˆ†å‰²", "å›¾åƒåˆ†ç±»"]
authors = [
    { name = "æ›¾é€¸å¤« Zeng Yifu" },
]
maintainers = [
    { name = "æ›¾é€¸å¤« Zeng Yifu" },
]
dependencies = [
    "click>=8.1",
    "ultralytics>=8.1.1",
    "gradio>=4.14.0",
    "gradio-imageslider",
    "opencv-python>=4.9.0.80",
    "matplotlib",
    "numpy>=1.24.4",
    "pandas",
    "pyyaml",
    "pillow>=10.1.0",
    "wget>=3.2",
    "rich>=13.7.0",
    "black",
    "mdformat",
    "build",
    "twine"
]


[project.scripts]
gradio-yolov8-det = "gradio_yolov8_det.gradio_yolov8_det_v2:entrypoint"


[project.urls]
"Bug Reports" = "https://gitee.com/CV_Lab/gradio-yolov8-det/issues"
"Funding" = "https://gitee.com/CV_Lab"
"Source" = "https://gitee.com/CV_Lab/gradio-yolov8-det"


[tool.setuptools]
packages = { find = { where = ["."], include = ["gradio_yolov8_det", "gradio_yolov8_det.*"]} }
package-data = { "gradio_yolov8_det" = ["**/*.css"], "gradio_yolov8_det.cls_name" = ["**/*.yaml", "**/*.csv", "**/*.txt"], "gradio_yolov8_det.model_config" = ["**/*.yaml", "**/*.csv", "**/*.txt"], "gradio_yolov8_det.img_examples" = ["**/*.jpg", "**/*.jpeg", "**/*.JPEG", "**/*.png"], "gradio_yolov8_det.icon" = ["**/*.ico"] }

