[tool.poetry]
name = "pychesstools"
version = "0.1.9"
description = "Data types for chess positions with support for many common variants."
authors = ["Sam <sbrobson@crimson.ua.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
rich = {version = "^13.7.0", optional = true}
mypy-extensions = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
