[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yt_pld"
version = "0.0.15"
authors = [
  { name="David", email="david2002belozerov@mail.ru" },
]
description = "Uploading videos to YouTube"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "selenium==4.16.0",
]
